---
# =============================================================================
# Node Exporter Role - Handlers
# =============================================================================

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart node_exporter
  service:
    name: node_exporter
    state: restarted
